apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-pvc
  namespace: expense-app
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi