apiVersion: v1
kind: PersistentVolume
metadata:
  name: expense-pv
  label:
    app: expense
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /mnt/expense-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi