server {
    listen 80;
    server_name 44.213.249.248;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass http://backend:8080/;
    }
    location /status {
        stub_status on;
        access_log off;
        #allow 127.0.0.1;
        #deny all;
    }
    location /health {
        stub_status on;
        access_log off;
    }
}
