server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /status {
        stub_status on;
        access_log off;
        #allow 127.0.0.1;
        #deny all;
    }
    location /health {
        stub_status on;
        access_log off;
    }
}